{{- $name := printf "%s-frontend" (include "taskboard.fullname" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "taskboard.selectorLabels" (dict "ctx" $ "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "taskboard.selectorLabels" (dict "ctx" $ "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskboard.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "taskboard.podSecurityContext" . | nindent 8 }}
        runAsUser: 101
      containers:
        - name: frontend
          image: {{ include "taskboard.image" (dict "ctx" $ "repository" .Values.frontend.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          env:
            - name: BACKEND_URL
              value: "http://{{ include "taskboard.fullname" . }}-backend:{{ .Values.backend.port }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            {{- include "taskboard.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-conf
          emptyDir: {}
